package kamkeel.plugin.Items;

import kamkeel.plugin.Blocks.ModBlocks;
import kamkeel.plugin.ModRegistries;
import net.minecraft.tags.BlockTags;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.Tier;
import net.minecraft.world.item.crafting.Ingredient;
import net.minecraft.world.food.FoodProperties;
import net.neoforged.neoforge.common.SimpleTier;
import net.neoforged.neoforge.registries.DeferredItem;

import java.util.ArrayList;
import java.util.List;

/**
 * Item registration. Ported from the 1.12.2 ModItems/ModWeapons registries;
 * every metadata variant of the old items is registered as a separate item.
 */
public final class ModItems {

    private ModItems() {}

    /** Every registered item, in registration order. */
    public static final List<DeferredItem<Item>> ALL = new ArrayList<>();
    /** Items grouped by creative tab. */
    public static final List<DeferredItem<Item>> MISC = new ArrayList<>();
    public static final List<DeferredItem<Item>> CARDS = new ArrayList<>();
    public static final List<DeferredItem<Item>> WEAPONS = new ArrayList<>();

    /** Generic weapon tier (1.12.2 PluginMaterial: 20000 uses, 6.0 speed, 7.0 damage). */
    public static final Tier WEAPON_TIER = new SimpleTier(
            BlockTags.INCORRECT_FOR_IRON_TOOL, 20000, 6.0F, 7.0F, 0,
            () -> Ingredient.EMPTY);

    /** Glass tier (1.12.2 GLASS: 20 uses, 16.0 speed, 10.0 damage). */
    public static final Tier GLASS_TIER = new SimpleTier(
            BlockTags.INCORRECT_FOR_STONE_TOOL, 20, 16.0F, 10.0F, 26,
            () -> Ingredient.EMPTY);

    /** Broken tier (1.12.2 brokenTool: 0 uses, 1.0 damage). */
    public static final Tier BROKEN_TIER = new SimpleTier(
            BlockTags.INCORRECT_FOR_IRON_TOOL, 0, 6.0F, 1.0F, 0,
            () -> Ingredient.EMPTY);

    /** Food stats shared by the 19 plugin apples (1.12.2: 4 hunger, 1.2 saturation, always edible). */
    public static final FoodProperties APPLE_FOOD = new FoodProperties.Builder()
            .nutrition(4).saturationModifier(1.2F).alwaysEdible().build();

    private static DeferredItem<Item> simple(String name, List<DeferredItem<Item>> tab) {
        DeferredItem<Item> it = ModRegistries.ITEMS.register(name, () -> new Item(new Item.Properties()));
        ALL.add(it);
        tab.add(it);
        return it;
    }

    private static DeferredItem<Item> weapon(String name, Tier tier, List<DeferredItem<Item>> tab) {
        DeferredItem<Item> it = ModRegistries.ITEMS.register(name, () -> new WeaponItem(tier, new Item.Properties()));
        ALL.add(it);
        tab.add(it);
        return it;
    }

    private static DeferredItem<Item> apple(String name, int variant) {
        DeferredItem<Item> it = ModRegistries.ITEMS.register(name, () -> new AppleItem(variant, new Item.Properties().food(APPLE_FOOD)));
        ALL.add(it);
        MISC.add(it);
        return it;
    }

    /** Resolve a registered item by its registry-name path. */
    public static DeferredItem<Item> find(String name) {
        for (DeferredItem<Item> it : ALL) {
            if (it.getId().getPath().equals(name)) {
                return it;
            }
        }
        return null;
    }

    /** Registers a BlockItem for every registered block. */
    public static void registerBlockItems() {
        for (var block : ModBlocks.ALL) {
            ModRegistries.ITEMS.registerSimpleBlockItem(block);
        }
    }

    public static void register() {
        // ---- Misc: materials ----
        simple("codium_ingot", MISC);
        simple("damascus_ingot", MISC);
        simple("deep_ingot", MISC);
        simple("energy_quartz", MISC);
        simple("dark_metal", MISC);
        simple("blue_steel", MISC);
        simple("jungle_ingot", MISC);
        simple("glass_shard", MISC);
        simple("imperial_gold", MISC);
        simple("aqua_ingot", MISC);
        simple("plug_ingot", MISC);
        simple("energy_catalyst", MISC);
        simple("hyper_catalyst", MISC);
        // ---- Misc: weapon parts ----
        simple("blue_longsword_custom_blade", MISC);
        simple("blue_longsword_custom_guard", MISC);
        simple("blue_longsword_custom_rod", MISC);
        simple("dark_dagger_custom_blade", MISC);
        simple("dark_dagger_custom_handle", MISC);
        simple("void_charm", MISC);
        simple("glass_disc", MISC);
        simple("glass_pan_handle", MISC);
        simple("glass_pan_binding", MISC);
        simple("jungle_axe_head", MISC);
        simple("jungle_axe_binding", MISC);
        simple("jungle_axe_rod", MISC);
        simple("treasure_cutlass_blade", MISC);
        simple("treasure_cutlass_binding", MISC);
        simple("treasure_cutlass_handle", MISC);
        simple("adaptors_spear_point", MISC);
        simple("adaptors_spear_binding", MISC);
        simple("adaptors_spear_handle", MISC);
        // ---- Misc: extras ----
        simple("treasuremap", MISC);
        simple("medkit", MISC);
        simple("bandages", MISC);
        simple("bell", MISC);
        simple("horn", MISC);
        simple("rope", MISC);
        simple("painkiller", MISC);
        simple("burrito", MISC);
        // ---- Misc: pills ----
        simple("pills_basic", MISC);
        simple("pills_advanced", MISC);
        simple("pills_pioneer", MISC);
        simple("pills_expertise", MISC);
        simple("pills_arcane", MISC);
        simple("pills_mystical", MISC);
        simple("pills_godly", MISC);
        simple("pills_split", MISC);
        simple("pills_fissure", MISC);
        simple("pills_shift", MISC);
        simple("pills_aqua", MISC);
        simple("pills_aura", MISC);
        simple("pills_core", MISC);
        simple("pills_corrupt", MISC);
        simple("pills_dark", MISC);
        simple("pills_fiery", MISC);
        simple("pills_freeze", MISC);
        simple("pills_heart", MISC);
        simple("pills_rebound", MISC);
        simple("pills_spirit", MISC);
        simple("pills_nature", MISC);
        simple("pills_desert", MISC);
        simple("pills_magma", MISC);
        simple("pills_extraone", MISC);
        simple("pills_extratwo", MISC);
        simple("pills_extrathree", MISC);
        simple("pills_extrafour", MISC);
        simple("pills_extrafive", MISC);
        simple("pills_extrasix", MISC);
        simple("pills_extraseven", MISC);
        simple("pills_extraeight", MISC);
        simple("pills_extranine", MISC);
        simple("pills_extraten", MISC);
        simple("pills_native", MISC);
        simple("pills_foreign", MISC);
        simple("pills_auraenergy", MISC);
        // ---- Misc: coins ----
        simple("coins_wood", MISC);
        simple("coins_stone", MISC);
        simple("coins_zinc", MISC);
        simple("coins_bronze", MISC);
        simple("coins_obsidian", MISC);
        simple("coins_iron", MISC);
        simple("coins_gold", MISC);
        simple("coins_platinum", MISC);
        simple("coins_emerald", MISC);
        simple("coins_ruby", MISC);
        simple("coins_diamond", MISC);
        simple("coins_amethyst", MISC);
        simple("coins_earth", MISC);
        simple("coins_other_amethyst", MISC);
        simple("coins_other_bronze", MISC);
        simple("coins_other_cobalt", MISC);
        simple("coins_other_diamond", MISC);
        simple("coins_other_emerald", MISC);
        simple("coins_other_gold", MISC);
        simple("coins_other_iron", MISC);
        simple("coins_other_obsidian", MISC);
        simple("coins_other_rose", MISC);
        simple("coins_other_ruby", MISC);
        simple("coins_other_wood", MISC);
        simple("coins_other2_dark_steel", MISC);
        simple("coins_other2_bronze", MISC);
        simple("coins_other2_diamond", MISC);
        simple("coins_other2_ruby", MISC);
        simple("coins_other2_silver", MISC);
        simple("coins_other2_copper", MISC);
        simple("coins_other2_emerald", MISC);
        simple("coins_other2_gold", MISC);
        // ---- Misc: balls ----
        simple("balls_one", MISC);
        simple("balls_two", MISC);
        simple("balls_three", MISC);
        simple("balls_four", MISC);
        simple("balls_five", MISC);
        simple("balls_six", MISC);
        simple("balls_seven", MISC);
        // ---- Misc: eyes ----
        simple("eyes_sharinganone", MISC);
        simple("eyes_sharingantwo", MISC);
        simple("eyes_sharinganthree", MISC);
        simple("eyes_byakugan", MISC);
        simple("eyes_rinnegan", MISC);
        // ---- Misc: apples (food) ----
        apple("classic_apple", 0);
        apple("founding_apple", 1);
        apple("vintage_apple", 2);
        apple("rage_apple", 3);
        apple("mend_apple", 4);
        apple("shield_apple", 5);
        apple("buffer_apple", 6);
        apple("swift_apple", 7);
        apple("boost_apple", 8);
        apple("alert_apple", 9);
        apple("element_apple", 10);
        apple("full_apple", 11);
        apple("drunk_apple", 12);
        apple("tank_apple", 13);
        apple("rotten_apple", 14);
        apple("corrupt_apple", 15);
        apple("reinforced_apple", 16);
        apple("toxic_apple", 17);
        apple("odd_apple", 18);
        // ---- Misc: artifacts ----
        simple("artifact_stoneegg", MISC);
        simple("artifact_primary", MISC);
        simple("artifact_amulet", MISC);
        simple("artifact_book", MISC);
        simple("artifact_totem", MISC);
        simple("artifact_necklace", MISC);
        simple("artifact_doll", MISC);
        simple("artifact_tooth", MISC);
        simple("artifact_trinity", MISC);
        simple("artifact_resonant_pearl", MISC);
        simple("artifact_energy_amplifier", MISC);
        simple("artifact_divinity", MISC);
        simple("artifact_magic_stew", MISC);
        simple("artifact_luck", MISC);
        simple("void_lasso", MISC);
        simple("dark_orb", MISC);
        simple("diamond_atom", MISC);
        simple("dungeon_chest_key", MISC);
        simple("seal_scroll", MISC);
        simple("charge_crystal", MISC);
        simple("journal_entry", MISC);
        simple("eyes_of_remnant", MISC);
        simple("lasr_eye", MISC);
        simple("dark_pendant", MISC);
        simple("magical_map", MISC);
        simple("mimic_fragment", MISC);
        simple("ward", MISC);
        simple("chalice", MISC);
        simple("warped_stone", MISC);
        simple("health_cube", MISC);
        simple("power_cube", MISC);
        simple("poison_cube", MISC);
        simple("midas_jewel", MISC);
        simple("necromancer", MISC);
        simple("ancient_rose", MISC);
        simple("shark_fin", MISC);
        simple("shark_necklace", MISC);
        simple("villium", MISC);
        simple("glacite_jewel", MISC);
        simple("goblin_egg", MISC);
        simple("petrified_stone", MISC);
        simple("crystal_geode", MISC);
        simple("plasma_nucleus", MISC);
        simple("kat_flower", MISC);
        simple("balance_scroll", MISC);
        simple("dark_scroll", MISC);
        simple("demon_scroll", MISC);
        simple("gold_scroll", MISC);
        simple("precursor_gem", MISC);
        simple("sorrow", MISC);
        simple("zem_orb", MISC);
        simple("forbidden_flower", MISC);
        simple("spirit_leap", MISC);
        simple("blood_skull", MISC);
        simple("master_skull", MISC);
        simple("krodo_orb", MISC);
        simple("golden_lasso", MISC);
        simple("heat_core", MISC);
        simple("codex", MISC);
        simple("poison_blob", MISC);
        simple("void_scroll", MISC);
        simple("blue_blood", MISC);
        simple("red_scarf", MISC);
        simple("veskin_hide", MISC);
        simple("crimson_vortex", MISC);
        simple("saving_grace", MISC);
        simple("bonzo_fragment", MISC);
        simple("livid_fragment", MISC);
        simple("prehistoric_egg", MISC);
        simple("queen_soul", MISC);
        simple("aspiring_leap", MISC);
        simple("reaper_orb", MISC);
        simple("hidden_zone", MISC);
        simple("lucky_dice", MISC);
        simple("moon_gem", MISC);
        simple("holy_stone", MISC);
        simple("dark_auction", MISC);
        simple("magma_bucket", MISC);
        simple("corleonite", MISC);
        simple("jungle_heart", MISC);
        simple("wither_catalyst", MISC);
        simple("lava_catalyst", MISC);
        simple("bountytrophy", MISC);
        simple("chilling", MISC);
        simple("stew_1", MISC);
        simple("stew_2", MISC);
        simple("flax", MISC);
        simple("gobletsilver", MISC);
        simple("gobletwood", MISC);
        simple("green_quartz", MISC);
        simple("rainbow_feather", MISC);
        simple("warp_gate", MISC);
        simple("net_ball", MISC);
        simple("grimoire", MISC);
        simple("soul_crystal", MISC);
        simple("judgement_core", MISC);
        simple("reaper_gem", MISC);
        simple("dead_catalyst", MISC);
        simple("ocean_orb", MISC);
        simple("abyssal_fruit", MISC);
        simple("forge_stone", MISC);
        simple("rare_amber", MISC);
        simple("amulet_of_cosolon", MISC);
        simple("angel_blessing", MISC);
        simple("anti_fear", MISC);
        simple("after_gem", MISC);
        simple("astral_dust", MISC);
        simple("astral_fruit", MISC);
        simple("cosmic_heart", MISC);
        simple("bastion_ring", MISC);
        simple("the_hadlium", MISC);
        simple("heaven_gem", MISC);
        simple("clock_of_time", MISC);
        simple("cosmic_scroll", MISC);
        simple("cursed_stone", MISC);
        simple("delay_ring", MISC);
        simple("earth_heart", MISC);
        simple("ectoplasm", MISC);
        simple("enders_hand", MISC);
        simple("enigmatic", MISC);
        simple("evil_essence", MISC);
        simple("anti_shuriken", MISC);
        simple("dimensional_eye", MISC);
        simple("fiery_heart", MISC);
        simple("glow_cube", MISC);
        simple("guardian_heart", MISC);
        simple("halo", MISC);
        simple("holy_locket", MISC);
        simple("ancient_flute", MISC);
        simple("hunter_belt", MISC);
        simple("identify_tome", MISC);
        simple("ignis_gem", MISC);
        simple("infernal_shield", MISC);
        simple("the_infinite", MISC);
        simple("inscriber", MISC);
        simple("dead_eye", MISC);
        simple("lore", MISC);
        simple("material_pouch", MISC);
        simple("remain_charm", MISC);
        simple("monster_charm", MISC);
        simple("earth_necklace", MISC);
        simple("ocean_stone", MISC);
        simple("pot_of_greed", MISC);
        simple("reflection_necklace", MISC);
        simple("zindaga_orb", MISC);
        simple("ring_of_fire", MISC);
        simple("ring_of_horror", MISC);
        simple("scarab_talisman", MISC);
        simple("shadow_glaive", MISC);
        simple("soul_devourer", MISC);
        simple("soul_matrix", MISC);
        simple("spatial_sign", MISC);
        simple("spore_sack", MISC);
        simple("stellar_catalyst", MISC);
        simple("unwritten", MISC);
        simple("the_all_knowing", MISC);
        simple("the_twist", MISC);
        simple("obsidian_skull", MISC);
        simple("twisted_core", MISC);
        simple("unholy_grail", MISC);
        simple("void_pearl", MISC);
        simple("whisp_of_chaos", MISC);
        simple("wormhole_mirror", MISC);
        simple("pierce_cannon", MISC);
        simple("the_dragonfly", MISC);
        simple("the_urchin_of_honor", MISC);
        simple("tribal_chain", MISC);
        simple("angry_pebble", MISC);
        simple("bark_amulet", MISC);
        simple("forbidden_tag", MISC);
        simple("chiromaw_barb", MISC);
        simple("chiromaw_egg", MISC);
        simple("dark_idol", MISC);
        simple("crazy_scroll", MISC);
        simple("urn_1", MISC);
        simple("urn_2", MISC);
        simple("urn_3", MISC);
        simple("lurker_skin", MISC);
        simple("magic_magnet", MISC);
        simple("the_how", MISC);
        simple("pyrad_flame", MISC);
        simple("ring_of_power", MISC);
        simple("ring_of_spirit", MISC);
        simple("ring_of_summoning", MISC);
        simple("seed_of_god", MISC);
        simple("rune_key", MISC);
        simple("sap", MISC);
        simple("spirit_totem", MISC);
        simple("swamp_talisman", MISC);
        simple("amanite", MISC);
        simple("beheaded_death", MISC);
        simple("deep_skull", MISC);
        simple("dice_of_fate", MISC);
        simple("dragon_egg", MISC);
        simple("fuming_book", MISC);
        simple("gold_slash", MISC);
        simple("inferno_vertex", MISC);
        simple("infinileap", MISC);
        simple("infinity_catalyst", MISC);
        simple("invertus", MISC);
        simple("mystic_orb", MISC);
        simple("overpower", MISC);
        simple("something", MISC);
        simple("soul_shard", MISC);
        simple("soul_string", MISC);
        simple("special_candle", MISC);
        simple("split_scroll", MISC);
        simple("subzero_inverter", MISC);
        simple("teleporter_pill", MISC);
        simple("tesselated_ender_pearl", MISC);
        simple("thunder_shards", MISC);
        simple("treasure_ring", MISC);
        simple("trident_scroll", MISC);
        simple("warden_heart", MISC);
        simple("wood_singularity", MISC);
        // ---- Cards ----
        simple("cardicon", CARDS);
        simple("hearts_ace", CARDS);
        simple("hearts_two", CARDS);
        simple("hearts_three", CARDS);
        simple("hearts_four", CARDS);
        simple("hearts_five", CARDS);
        simple("hearts_six", CARDS);
        simple("hearts_seven", CARDS);
        simple("hearts_eight", CARDS);
        simple("hearts_nine", CARDS);
        simple("hearts_ten", CARDS);
        simple("hearts_jack", CARDS);
        simple("hearts_queen", CARDS);
        simple("hearts_king", CARDS);
        simple("diamond_ace", CARDS);
        simple("diamond_two", CARDS);
        simple("diamond_three", CARDS);
        simple("diamond_four", CARDS);
        simple("diamond_five", CARDS);
        simple("diamond_six", CARDS);
        simple("diamond_seven", CARDS);
        simple("diamond_eight", CARDS);
        simple("diamond_nine", CARDS);
        simple("diamond_ten", CARDS);
        simple("diamond_jack", CARDS);
        simple("diamond_queen", CARDS);
        simple("diamond_king", CARDS);
        simple("spade_ace", CARDS);
        simple("spade_two", CARDS);
        simple("spade_three", CARDS);
        simple("spade_four", CARDS);
        simple("spade_five", CARDS);
        simple("spade_six", CARDS);
        simple("spade_seven", CARDS);
        simple("spade_eight", CARDS);
        simple("spade_nine", CARDS);
        simple("spade_ten", CARDS);
        simple("spade_jack", CARDS);
        simple("spade_queen", CARDS);
        simple("spade_king", CARDS);
        simple("clubs_ace", CARDS);
        simple("clubs_two", CARDS);
        simple("clubs_three", CARDS);
        simple("clubs_four", CARDS);
        simple("clubs_five", CARDS);
        simple("clubs_six", CARDS);
        simple("clubs_seven", CARDS);
        simple("clubs_eight", CARDS);
        simple("clubs_nine", CARDS);
        simple("clubs_ten", CARDS);
        simple("clubs_jack", CARDS);
        simple("clubs_queen", CARDS);
        simple("clubs_king", CARDS);
        simple("joker_red", CARDS);
        simple("joker_black", CARDS);
        simple("cards_whisperer", CARDS);
        simple("cards_daybreak", CARDS);
        simple("cards_awen", CARDS);
        simple("cards_radiance", CARDS);
        // ---- Weapons: energy attacks ----
        simple("voidrasenshuriken", WEAPONS);
        simple("massiverasengan", WEAPONS);
        simple("massiverasengan_spin", WEAPONS);
        simple("dark_rasengan", WEAPONS);
        simple("dark_rasengan_spin", WEAPONS);
        simple("rasengan", WEAPONS);
        simple("rasengan_spin", WEAPONS);
        // ---- Weapons ----
        weapon("debug_dagger_broken", BROKEN_TIER, WEAPONS);
        weapon("reverse_debug_dagger_broken", BROKEN_TIER, WEAPONS);
        weapon("debug_dagger", WEAPON_TIER, WEAPONS);
        weapon("reverse_debug_dagger", WEAPON_TIER, WEAPONS);
        weapon("debug_dagger_energized", WEAPON_TIER, WEAPONS);
        weapon("reverse_debug_dagger_energized", WEAPON_TIER, WEAPONS);
        weapon("dark_dagger_custom_broken", BROKEN_TIER, WEAPONS);
        weapon("reverse_dark_dagger_custom_broken", BROKEN_TIER, WEAPONS);
        weapon("blue_longsword_custom_broken", BROKEN_TIER, WEAPONS);
        weapon("jungle_axe_custom_broken", BROKEN_TIER, WEAPONS);
        weapon("glass_pan_custom_broken", BROKEN_TIER, WEAPONS);
        weapon("treasure_cutlass_broken", BROKEN_TIER, WEAPONS);
        weapon("adaptors_spear_broken", BROKEN_TIER, WEAPONS);
        weapon("blue_longsword_custom", WEAPON_TIER, WEAPONS);
        weapon("blue_longsword_custom_energized", WEAPON_TIER, WEAPONS);
        weapon("jungle_axe_custom", WEAPON_TIER, WEAPONS);
        weapon("jungle_axe_custom_energized", WEAPON_TIER, WEAPONS);
        weapon("glass_pan_custom", WEAPON_TIER, WEAPONS);
        weapon("glass_pan_custom_energized", WEAPON_TIER, WEAPONS);
        weapon("dark_scythe", WEAPON_TIER, WEAPONS);
        weapon("dark_scythe_energized", WEAPON_TIER, WEAPONS);
        weapon("dark_dagger_custom", WEAPON_TIER, WEAPONS);
        weapon("reverse_dark_dagger_custom", WEAPON_TIER, WEAPONS);
        weapon("dark_dagger_custom_energized", WEAPON_TIER, WEAPONS);
        weapon("reverse_dark_dagger_custom_energized", WEAPON_TIER, WEAPONS);
        weapon("treasure_cutlass", WEAPON_TIER, WEAPONS);
        weapon("treasure_cutlass_energized", WEAPON_TIER, WEAPONS);
        weapon("adaptors_spear", WEAPON_TIER, WEAPONS);
        weapon("adaptors_spear_energized", WEAPON_TIER, WEAPONS);
        weapon("aurora_katana", WEAPON_TIER, WEAPONS);
        weapon("aurora_katana_energized", WEAPON_TIER, WEAPONS);
        weapon("codium_longsword", WEAPON_TIER, WEAPONS);
        weapon("codium_longsword_energized", WEAPON_TIER, WEAPONS);
        weapon("glass_blade", GLASS_TIER, WEAPONS);
        weapon("glass_cutlass", GLASS_TIER, WEAPONS);
        weapon("glass_kunai", GLASS_TIER, WEAPONS);
        weapon("reverse_glass_kunai", GLASS_TIER, WEAPONS);
        weapon("glass_dagger", GLASS_TIER, WEAPONS);
        weapon("reverse_glass_dagger", GLASS_TIER, WEAPONS);
        weapon("crystal_spear", GLASS_TIER, WEAPONS);
        weapon("hunter_knife", WEAPON_TIER, WEAPONS);
        weapon("reverse_hunter_knife", WEAPON_TIER, WEAPONS);
        weapon("spirit_knife", WEAPON_TIER, WEAPONS);
        weapon("reverse_spirit_knife", WEAPON_TIER, WEAPONS);
        weapon("eternal_knife", WEAPON_TIER, WEAPONS);
        weapon("reverse_eternal_knife", WEAPON_TIER, WEAPONS);
        weapon("dark_dagger", WEAPON_TIER, WEAPONS);
        weapon("reverse_dark_dagger", WEAPON_TIER, WEAPONS);
        weapon("silver_fang", WEAPON_TIER, WEAPONS);
        weapon("reverse_silver_fang", WEAPON_TIER, WEAPONS);
        weapon("earth_shard", WEAPON_TIER, WEAPONS);
        weapon("reverse_earth_shard", WEAPON_TIER, WEAPONS);
        weapon("livid_dagger", WEAPON_TIER, WEAPONS);
        weapon("reverse_livid_dagger", WEAPON_TIER, WEAPONS);
        weapon("amorth_dagger", WEAPON_TIER, WEAPONS);
        weapon("reverse_amorth_dagger", WEAPON_TIER, WEAPONS);
        weapon("barrow_dagger", WEAPON_TIER, WEAPONS);
        weapon("reverse_barrow_dagger", WEAPON_TIER, WEAPONS);
        weapon("basrol_dagger", WEAPON_TIER, WEAPONS);
        weapon("reverse_basrol_dagger", WEAPON_TIER, WEAPONS);
        weapon("bluesteel_dagger", WEAPON_TIER, WEAPONS);
        weapon("reverse_bluesteel_dagger", WEAPON_TIER, WEAPONS);
        weapon("corsair_dagger", WEAPON_TIER, WEAPONS);
        weapon("reverse_corsair_dagger", WEAPON_TIER, WEAPONS);
        weapon("cutlin_dagger", WEAPON_TIER, WEAPONS);
        weapon("reverse_cutlin_dagger", WEAPON_TIER, WEAPONS);
        weapon("cystel_dagger", WEAPON_TIER, WEAPONS);
        weapon("reverse_cystel_dagger", WEAPON_TIER, WEAPONS);
        weapon("daedra_dagger", WEAPON_TIER, WEAPONS);
        weapon("reverse_daedra_dagger", WEAPON_TIER, WEAPONS);
        weapon("dale_dagger", WEAPON_TIER, WEAPONS);
        weapon("reverse_dale_dagger", WEAPON_TIER, WEAPONS);
        weapon("dated_dagger", WEAPON_TIER, WEAPONS);
        weapon("reverse_dated_dagger", WEAPON_TIER, WEAPONS);
        weapon("doltek_dagger", WEAPON_TIER, WEAPONS);
        weapon("reverse_doltek_dagger", WEAPON_TIER, WEAPONS);
        weapon("dyvel_dagger", WEAPON_TIER, WEAPONS);
        weapon("reverse_dyvel_dagger", WEAPON_TIER, WEAPONS);
        weapon("invar_dagger", WEAPON_TIER, WEAPONS);
        weapon("reverse_invar_dagger", WEAPON_TIER, WEAPONS);
        weapon("kevlo_dagger", WEAPON_TIER, WEAPONS);
        weapon("reverse_kevlo_dagger", WEAPON_TIER, WEAPONS);
        weapon("light_dagger", WEAPON_TIER, WEAPONS);
        weapon("reverse_light_dagger", WEAPON_TIER, WEAPONS);
        weapon("orc_dagger", WEAPON_TIER, WEAPONS);
        weapon("reverse_orc_dagger", WEAPON_TIER, WEAPONS);
        weapon("primal_dagger", WEAPON_TIER, WEAPONS);
        weapon("reverse_primal_dagger", WEAPON_TIER, WEAPONS);
        weapon("rol_dagger", WEAPON_TIER, WEAPONS);
        weapon("reverse_rol_dagger", WEAPON_TIER, WEAPONS);
        weapon("ronin_dagger", WEAPON_TIER, WEAPONS);
        weapon("reverse_ronin_dagger", WEAPON_TIER, WEAPONS);
        weapon("rustic_dagger", WEAPON_TIER, WEAPONS);
        weapon("reverse_rustic_dagger", WEAPON_TIER, WEAPONS);
        weapon("silver_dagger", WEAPON_TIER, WEAPONS);
        weapon("reverse_silver_dagger", WEAPON_TIER, WEAPONS);
        weapon("sinbar_dagger", WEAPON_TIER, WEAPONS);
        weapon("reverse_sinbar_dagger", WEAPON_TIER, WEAPONS);
        weapon("troy_dagger", WEAPON_TIER, WEAPONS);
        weapon("reverse_troy_dagger", WEAPON_TIER, WEAPONS);
        weapon("vulcan_dagger", WEAPON_TIER, WEAPONS);
        weapon("reverse_vulcan_dagger", WEAPON_TIER, WEAPONS);
        weapon("wildscum_dagger", WEAPON_TIER, WEAPONS);
        weapon("reverse_wildscum_dagger", WEAPON_TIER, WEAPONS);
        weapon("obsidian_dagger", WEAPON_TIER, WEAPONS);
        weapon("reverse_obsidian_dagger", WEAPON_TIER, WEAPONS);
        weapon("maeve_dagger", WEAPON_TIER, WEAPONS);
        weapon("reverse_maeve_dagger", WEAPON_TIER, WEAPONS);
        weapon("brass_dagger", WEAPON_TIER, WEAPONS);
        weapon("reverse_brass_dagger", WEAPON_TIER, WEAPONS);
        weapon("cactus_knife", WEAPON_TIER, WEAPONS);
        weapon("reverse_cactus_knife", WEAPON_TIER, WEAPONS);
        weapon("ritual_dagger", WEAPON_TIER, WEAPONS);
        weapon("reverse_ritual_dagger", WEAPON_TIER, WEAPONS);
        weapon("vulcan_polearm", WEAPON_TIER, WEAPONS);
        weapon("cystel_polearm", WEAPON_TIER, WEAPONS);
        weapon("elvo_polearm", WEAPON_TIER, WEAPONS);
        weapon("orc_polearm", WEAPON_TIER, WEAPONS);
        weapon("rol_polearm", WEAPON_TIER, WEAPONS);
        weapon("silver_polearm", WEAPON_TIER, WEAPONS);
        weapon("blue_steel_spear", WEAPON_TIER, WEAPONS);
        weapon("corsair_spear", WEAPON_TIER, WEAPONS);
        weapon("cutlin_spear", WEAPON_TIER, WEAPONS);
        weapon("cystel_spear", WEAPON_TIER, WEAPONS);
        weapon("dale_spear", WEAPON_TIER, WEAPONS);
        weapon("dark_steel_spear", WEAPON_TIER, WEAPONS);
        weapon("doltek_spear", WEAPON_TIER, WEAPONS);
        weapon("dyvel_spear", WEAPON_TIER, WEAPONS);
        weapon("elvo_spear", WEAPON_TIER, WEAPONS);
        weapon("hell_spear", WEAPON_TIER, WEAPONS);
        weapon("invar_spear", WEAPON_TIER, WEAPONS);
        weapon("jungle_spear", WEAPON_TIER, WEAPONS);
        weapon("kelvo_spear", WEAPON_TIER, WEAPONS);
        weapon("light_spear", WEAPON_TIER, WEAPONS);
        weapon("orc_spear", WEAPON_TIER, WEAPONS);
        weapon("primal_spear", WEAPON_TIER, WEAPONS);
        weapon("rol_spear", WEAPON_TIER, WEAPONS);
        weapon("ronin_spear", WEAPON_TIER, WEAPONS);
        weapon("rustic_spear", WEAPON_TIER, WEAPONS);
        weapon("silver_spear", WEAPON_TIER, WEAPONS);
        weapon("sinbar_spear", WEAPON_TIER, WEAPONS);
        weapon("uruk_spear", WEAPON_TIER, WEAPONS);
        weapon("vulcan_spear", WEAPON_TIER, WEAPONS);
        weapon("wildscum_spear", WEAPON_TIER, WEAPONS);
        weapon("blue_steel_pike", WEAPON_TIER, WEAPONS);
        weapon("dale_pike", WEAPON_TIER, WEAPONS);
        weapon("doltek_pike", WEAPON_TIER, WEAPONS);
        weapon("invar_pike", WEAPON_TIER, WEAPONS);
        weapon("kevlo_pike", WEAPON_TIER, WEAPONS);
        weapon("peldris_trident", WEAPON_TIER, WEAPONS);
        weapon("rock_pike", WEAPON_TIER, WEAPONS);
        weapon("rol_pike", WEAPON_TIER, WEAPONS);
        weapon("rustic_pike", WEAPON_TIER, WEAPONS);
        weapon("uruk_pike", WEAPON_TIER, WEAPONS);
        weapon("vulcan_pike", WEAPON_TIER, WEAPONS);
        weapon("wildscum_pike", WEAPON_TIER, WEAPONS);
        weapon("primal_waraxe", WEAPON_TIER, WEAPONS);
        weapon("losar_waraxe", WEAPON_TIER, WEAPONS);
        weapon("rol_waraxe", WEAPON_TIER, WEAPONS);
        weapon("dale_waraxe", WEAPON_TIER, WEAPONS);
        weapon("hell_waraxe", WEAPON_TIER, WEAPONS);
        weapon("kevlo_waraxe", WEAPON_TIER, WEAPONS);
        weapon("orc_waraxe", WEAPON_TIER, WEAPONS);
        weapon("rock_waraxe", WEAPON_TIER, WEAPONS);
        weapon("ronin_waraxe", WEAPON_TIER, WEAPONS);
        weapon("uruk_waraxe", WEAPON_TIER, WEAPONS);
        weapon("wildscum_waraxe", WEAPON_TIER, WEAPONS);
        weapon("raider_axe", WEAPON_TIER, WEAPONS);
        weapon("revenant_pickaxe", WEAPON_TIER, WEAPONS);
        weapon("woodsman", WEAPON_TIER, WEAPONS);
        weapon("dark_metal_axe", WEAPON_TIER, WEAPONS);
        weapon("floral_axe", WEAPON_TIER, WEAPONS);
        weapon("leaf_axe", WEAPON_TIER, WEAPONS);
        weapon("rusty_axe", WEAPON_TIER, WEAPONS);
        weapon("mythic_axe", WEAPON_TIER, WEAPONS);
        weapon("melon_dicer", WEAPON_TIER, WEAPONS);
        weapon("blood_axe", WEAPON_TIER, WEAPONS);
        weapon("darkwood_axe", WEAPON_TIER, WEAPONS);
        weapon("mithril_pickaxe", WEAPON_TIER, WEAPONS);
        weapon("mayan_pickaxe", WEAPON_TIER, WEAPONS);
        weapon("heavy_axe", WEAPON_TIER, WEAPONS);
        weapon("mayan_axe", WEAPON_TIER, WEAPONS);
        weapon("blue_steel_axe", WEAPON_TIER, WEAPONS);
        weapon("doltek_axe", WEAPON_TIER, WEAPONS);
        weapon("elvo_axe", WEAPON_TIER, WEAPONS);
        weapon("invar_axe", WEAPON_TIER, WEAPONS);
        weapon("light_axe", WEAPON_TIER, WEAPONS);
        weapon("native_axe", WEAPON_TIER, WEAPONS);
        weapon("orc_axe", WEAPON_TIER, WEAPONS);
        weapon("silver_axe", WEAPON_TIER, WEAPONS);
        weapon("uruk_axe", WEAPON_TIER, WEAPONS);
        weapon("wildscum_axe", WEAPON_TIER, WEAPONS);
        weapon("blue_steel__battleaxe", WEAPON_TIER, WEAPONS);
        weapon("corsair_battleaxe", WEAPON_TIER, WEAPONS);
        weapon("dol_battleaxe", WEAPON_TIER, WEAPONS);
        weapon("doltek_battleaxe", WEAPON_TIER, WEAPONS);
        weapon("elvo_battleaxe", WEAPON_TIER, WEAPONS);
        weapon("hell_battleaxe", WEAPON_TIER, WEAPONS);
        weapon("invar_battleaxe", WEAPON_TIER, WEAPONS);
        weapon("pig_axe", WEAPON_TIER, WEAPONS);
        weapon("cow_axe", WEAPON_TIER, WEAPONS);
        weapon("fungi_cutter", WEAPON_TIER, WEAPONS);
        weapon("jungle_pickaxe", WEAPON_TIER, WEAPONS);
        weapon("blue_steel_hammer", WEAPON_TIER, WEAPONS);
        weapon("cutlin_hammer", WEAPON_TIER, WEAPONS);
        weapon("doltek_hammer", WEAPON_TIER, WEAPONS);
        weapon("elvo_hammer", WEAPON_TIER, WEAPONS);
        weapon("gondor_hammer", WEAPON_TIER, WEAPONS);
        weapon("hell_hammer", WEAPON_TIER, WEAPONS);
        weapon("invar_hammer", WEAPON_TIER, WEAPONS);
        weapon("kevlo_hammer", WEAPON_TIER, WEAPONS);
        weapon("orc_hammer", WEAPON_TIER, WEAPONS);
        weapon("rock_hammer", WEAPON_TIER, WEAPONS);
        weapon("uruk_hammer", WEAPON_TIER, WEAPONS);
        weapon("wildscum_hammer", WEAPON_TIER, WEAPONS);
        weapon("amethyst_sword", WEAPON_TIER, WEAPONS);
        weapon("dragon_sword", WEAPON_TIER, WEAPONS);
        weapon("resin_sword", WEAPON_TIER, WEAPONS);
        weapon("cleaver", WEAPON_TIER, WEAPONS);
        weapon("edible_mace", WEAPON_TIER, WEAPONS);
        weapon("ember_mace", WEAPON_TIER, WEAPONS);
        weapon("emerald_sword", WEAPON_TIER, WEAPONS);
        weapon("endstone_sword", WEAPON_TIER, WEAPONS);
        weapon("dark_metal_sword", WEAPON_TIER, WEAPONS);
        weapon("onyx_sword", WEAPON_TIER, WEAPONS);
        weapon("ivar_sword", WEAPON_TIER, WEAPONS);
        weapon("flame_sword", WEAPON_TIER, WEAPONS);
        weapon("golem_sword", WEAPON_TIER, WEAPONS);
        weapon("kitchen_knife", WEAPON_TIER, WEAPONS);
        weapon("spider_sword", WEAPON_TIER, WEAPONS);
        weapon("holy_sword", WEAPON_TIER, WEAPONS);
        weapon("bronze_cutlass", WEAPON_TIER, WEAPONS);
        weapon("prismarine_sword", WEAPON_TIER, WEAPONS);
        weapon("midnight_fang", WEAPON_TIER, WEAPONS);
        weapon("rogue_sword", WEAPON_TIER, WEAPONS);
        weapon("scorpion_foil", WEAPON_TIER, WEAPONS);
        weapon("shaman_sword", WEAPON_TIER, WEAPONS);
        weapon("silk_edge", WEAPON_TIER, WEAPONS);
        weapon("zero_sword", WEAPON_TIER, WEAPONS);
        weapon("tactical_sword", WEAPON_TIER, WEAPONS);
        weapon("undead_sword", WEAPON_TIER, WEAPONS);
        weapon("ice_sword", WEAPON_TIER, WEAPONS);
        weapon("crimson_cutlass", WEAPON_TIER, WEAPONS);
        weapon("golden_cutlass", WEAPON_TIER, WEAPONS);
        weapon("void_sword", WEAPON_TIER, WEAPONS);
        weapon("fury_sword", WEAPON_TIER, WEAPONS);
        weapon("chaos_sword", WEAPON_TIER, WEAPONS);
        weapon("aspect_sword", WEAPON_TIER, WEAPONS);
        weapon("fiery_wand", WEAPON_TIER, WEAPONS);
        weapon("jade_dagger", WEAPON_TIER, WEAPONS);
        weapon("dark_steel_sword", WEAPON_TIER, WEAPONS);
        weapon("silver_rapier", WEAPON_TIER, WEAPONS);
        weapon("ingite", WEAPON_TIER, WEAPONS);
        weapon("golem_sword_2", WEAPON_TIER, WEAPONS);
        weapon("thorn_knife", WEAPON_TIER, WEAPONS);
        weapon("leaping_sword", WEAPON_TIER, WEAPONS);
        weapon("glass_reaper", WEAPON_TIER, WEAPONS);
        weapon("something_sword", WEAPON_TIER, WEAPONS);
        weapon("casian", WEAPON_TIER, WEAPONS);
        weapon("prismarine_cutlass", WEAPON_TIER, WEAPONS);
        weapon("sacred_reaper", WEAPON_TIER, WEAPONS);
        weapon("revenant_sword", WEAPON_TIER, WEAPONS);
        weapon("injection", WEAPON_TIER, WEAPONS);
        weapon("white_light", WEAPON_TIER, WEAPONS);
        weapon("weaver_sword", WEAPON_TIER, WEAPONS);
        weapon("rotten_sword", WEAPON_TIER, WEAPONS);
        weapon("ooze_sword", WEAPON_TIER, WEAPONS);
        weapon("crystal_sword", WEAPON_TIER, WEAPONS);
        weapon("energy_saber", WEAPON_TIER, WEAPONS);
        weapon("trinity_wand", WEAPON_TIER, WEAPONS);
        weapon("astraea", WEAPON_TIER, WEAPONS);
        weapon("dreadlord_sword", WEAPON_TIER, WEAPONS);
        weapon("fel_sword", WEAPON_TIER, WEAPONS);
        weapon("hyperion", WEAPON_TIER, WEAPONS);
        weapon("necromancer_sword", WEAPON_TIER, WEAPONS);
        weapon("necron_blade", WEAPON_TIER, WEAPONS);
        weapon("silent_death", WEAPON_TIER, WEAPONS);
        weapon("knight_cutlass", WEAPON_TIER, WEAPONS);
        weapon("poison_cutlass", WEAPON_TIER, WEAPONS);
        weapon("cryptic_sword", WEAPON_TIER, WEAPONS);
        weapon("the_necromancer", WEAPON_TIER, WEAPONS);
        weapon("earth_sword", WEAPON_TIER, WEAPONS);
        weapon("forest_roots", WEAPON_TIER, WEAPONS);
        weapon("the_vampire", WEAPON_TIER, WEAPONS);
        weapon("blacksmith_hammer", WEAPON_TIER, WEAPONS);
        weapon("amorth_sword", WEAPON_TIER, WEAPONS);
        weapon("blue_steel_sword", WEAPON_TIER, WEAPONS);
        weapon("brass_sword", WEAPON_TIER, WEAPONS);
        weapon("corsair_sword", WEAPON_TIER, WEAPONS);
        weapon("cystel_sword", WEAPON_TIER, WEAPONS);
        weapon("dale_sword", WEAPON_TIER, WEAPONS);
        weapon("dark_steel_sword_2", WEAPON_TIER, WEAPONS);
        weapon("doltek_sword", WEAPON_TIER, WEAPONS);
        weapon("dyvel_sword", WEAPON_TIER, WEAPONS);
        weapon("elvo_sword", WEAPON_TIER, WEAPONS);
        weapon("glamdo_sword", WEAPON_TIER, WEAPONS);
        weapon("gondor_sword", WEAPON_TIER, WEAPONS);
        weapon("heavy_orc_sword", WEAPON_TIER, WEAPONS);
        weapon("hell_sword", WEAPON_TIER, WEAPONS);
        weapon("invar_sword", WEAPON_TIER, WEAPONS);
        weapon("jungle_sword", WEAPON_TIER, WEAPONS);
        weapon("kevlo_sword", WEAPON_TIER, WEAPONS);
        weapon("light_silver_sword", WEAPON_TIER, WEAPONS);
        weapon("light_sword", WEAPON_TIER, WEAPONS);
        weapon("rol_sword", WEAPON_TIER, WEAPONS);
        weapon("ronin_sword", WEAPON_TIER, WEAPONS);
        weapon("rustic_sword", WEAPON_TIER, WEAPONS);
        weapon("silver_sword", WEAPON_TIER, WEAPONS);
        weapon("sinbar_sword", WEAPON_TIER, WEAPONS);
        weapon("sinbar_sword_2", WEAPON_TIER, WEAPONS);
        weapon("wildscum_sword", WEAPON_TIER, WEAPONS);
        weapon("vulcan_scimitar", WEAPON_TIER, WEAPONS);
        weapon("cutlin_scimitar", WEAPON_TIER, WEAPONS);
        weapon("orc_scimitar", WEAPON_TIER, WEAPONS);
        weapon("orc_scimitar_2", WEAPON_TIER, WEAPONS);
        weapon("rock_scimitar", WEAPON_TIER, WEAPONS);
        weapon("rustic_sickle", WEAPON_TIER, WEAPONS);
        weapon("black_steel_mace", WEAPON_TIER, WEAPONS);
        weapon("rock_mace", WEAPON_TIER, WEAPONS);
        weapon("burnt_mace", WEAPON_TIER, WEAPONS);
        weapon("vulcan_mace", WEAPON_TIER, WEAPONS);
        weapon("sauro_mace", WEAPON_TIER, WEAPONS);
        weapon("vorpal_katana", WEAPON_TIER, WEAPONS);
        weapon("conjuring", WEAPON_TIER, WEAPONS);
        weapon("ruin_dagger", WEAPON_TIER, WEAPONS);
        weapon("valkyrie", WEAPON_TIER, WEAPONS);
        weapon("silver_cutlass", WEAPON_TIER, WEAPONS);
        weapon("revenant", WEAPON_TIER, WEAPONS);
        weapon("warped_sword", WEAPON_TIER, WEAPONS);
        weapon("wither_cloak_sword", WEAPON_TIER, WEAPONS);
        weapon("crypt_sword", WEAPON_TIER, WEAPONS);
        weapon("blaze_sword", WEAPON_TIER, WEAPONS);
        weapon("nether_soul_sword", WEAPON_TIER, WEAPONS);
        weapon("atonement", WEAPON_TIER, WEAPONS);
        weapon("valonite_sword", WEAPON_TIER, WEAPONS);
        weapon("corrosive_sword", WEAPON_TIER, WEAPONS);
        weapon("kuruzi_bat", WEAPON_TIER, WEAPONS);
        weapon("nether_cutlass", WEAPON_TIER, WEAPONS);
        weapon("light_katana", WEAPON_TIER, WEAPONS);
        weapon("jungle_katana", WEAPON_TIER, WEAPONS);
        weapon("wildscum_katana", WEAPON_TIER, WEAPONS);
        weapon("dreadlord_broadsword", WEAPON_TIER, WEAPONS);
        weapon("fel_broadsword", WEAPON_TIER, WEAPONS);
        weapon("amorth_broadsword", WEAPON_TIER, WEAPONS);
        weapon("cystel_broadsword", WEAPON_TIER, WEAPONS);
        weapon("gondor_broadsword", WEAPON_TIER, WEAPONS);
        weapon("kevlo_broadsword", WEAPON_TIER, WEAPONS);
        weapon("orc_broadsword", WEAPON_TIER, WEAPONS);
        weapon("rock_broadsword", WEAPON_TIER, WEAPONS);
        weapon("silver_broadsword", WEAPON_TIER, WEAPONS);
        weapon("sinbar_broadsword", WEAPON_TIER, WEAPONS);
        weapon("uruk_broadsword", WEAPON_TIER, WEAPONS);
        weapon("leaf_staff", WEAPON_TIER, WEAPONS);
        weapon("jungle_staff", WEAPON_TIER, WEAPONS);
        weapon("light_staff", WEAPON_TIER, WEAPONS);
        weapon("blood_scythe", WEAPON_TIER, WEAPONS);
        weapon("ice_scyte", WEAPON_TIER, WEAPONS);
        weapon("frozen_scythe", WEAPON_TIER, WEAPONS);
        weapon("energy_scyte", WEAPON_TIER, WEAPONS);
        weapon("mayan_scythe", WEAPON_TIER, WEAPONS);
        weapon("carrot_scythe", WEAPON_TIER, WEAPONS);
        weapon("mythic_scythe", WEAPON_TIER, WEAPONS);
        weapon("newton_scythe", WEAPON_TIER, WEAPONS);
        weapon("evil_scythe", WEAPON_TIER, WEAPONS);
        weapon("crook", WEAPON_TIER, WEAPONS);
        weapon("soul_crook", WEAPON_TIER, WEAPONS);
        weapon("quartz_claw", WEAPON_TIER, WEAPONS);
        weapon("gold_claws", WEAPON_TIER, WEAPONS);
        weapon("serrated_claws", WEAPON_TIER, WEAPONS);
        weapon("iron_claws", WEAPON_TIER, WEAPONS);
        weapon("blackstone_shield", WEAPON_TIER, WEAPONS);
        weapon("blue_steel_shield", WEAPON_TIER, WEAPONS);
        weapon("brass_shield", WEAPON_TIER, WEAPONS);
        weapon("constellas_shield", WEAPON_TIER, WEAPONS);
        weapon("copper_shield", WEAPON_TIER, WEAPONS);
        weapon("corsair_shield", WEAPON_TIER, WEAPONS);
        weapon("cutlin_shield", WEAPON_TIER, WEAPONS);
        weapon("dark_shield", WEAPON_TIER, WEAPONS);
        weapon("dark_steel_shield", WEAPON_TIER, WEAPONS);
        weapon("deep_shield", WEAPON_TIER, WEAPONS);
        weapon("dread_shield", WEAPON_TIER, WEAPONS);
        weapon("electrum_shield", WEAPON_TIER, WEAPONS);
        weapon("elementium_shield", WEAPON_TIER, WEAPONS);
        weapon("elvo_shield", WEAPON_TIER, WEAPONS);
        weapon("ender_shield", WEAPON_TIER, WEAPONS);
        weapon("flux_shield", WEAPON_TIER, WEAPONS);
        weapon("gold_shield", WEAPON_TIER, WEAPONS);
        weapon("hard_diamond_shield", WEAPON_TIER, WEAPONS);
        weapon("heavy_shield", WEAPON_TIER, WEAPONS);
        weapon("heavy_stone_shield", WEAPON_TIER, WEAPONS);
        weapon("invar_shield", WEAPON_TIER, WEAPONS);
        weapon("jungle_shield", WEAPON_TIER, WEAPONS);
        weapon("knight_shield", WEAPON_TIER, WEAPONS);
        weapon("koi_shield", WEAPON_TIER, WEAPONS);
        weapon("lapis_shield", WEAPON_TIER, WEAPONS);
        weapon("lead_shield", WEAPON_TIER, WEAPONS);
        weapon("light_shield", WEAPON_TIER, WEAPONS);
        weapon("manasteel_shield", WEAPON_TIER, WEAPONS);
        weapon("obsidian_shield", WEAPON_TIER, WEAPONS);
        weapon("orc_shield", WEAPON_TIER, WEAPONS);
        weapon("platinum_shield", WEAPON_TIER, WEAPONS);
        weapon("primal_shield", WEAPON_TIER, WEAPONS);
        weapon("rock_shield", WEAPON_TIER, WEAPONS);
        weapon("rol_shield", WEAPON_TIER, WEAPONS);
        weapon("rose_shield", WEAPON_TIER, WEAPONS);
        weapon("royal_shield", WEAPON_TIER, WEAPONS);
        weapon("rune_shield", WEAPON_TIER, WEAPONS);
        weapon("sandstone_shield", WEAPON_TIER, WEAPONS);
        weapon("signalum_shield", WEAPON_TIER, WEAPONS);
        weapon("silver_shield", WEAPON_TIER, WEAPONS);
        weapon("sinbar_shield", WEAPON_TIER, WEAPONS);
        weapon("spectral_shield", WEAPON_TIER, WEAPONS);
        weapon("steel_shield", WEAPON_TIER, WEAPONS);
        weapon("stone_shield", WEAPON_TIER, WEAPONS);
        weapon("terrasteel_shield", WEAPON_TIER, WEAPONS);
        weapon("tin_shield", WEAPON_TIER, WEAPONS);
        weapon("turtle_shield", WEAPON_TIER, WEAPONS);
        weapon("uruk_shield", WEAPON_TIER, WEAPONS);
        weapon("void_shield", WEAPON_TIER, WEAPONS);
        weapon("wood_shield", WEAPON_TIER, WEAPONS);
        // ---- Weapons: bows ----
        simple("dark_metal_bow", WEAPONS);
        simple("death_bow", WEAPONS);
        simple("end_stone_bow", WEAPONS);
        simple("explosive_bow", WEAPONS);
        simple("hurricane_bow", WEAPONS);
        simple("magma_bow", WEAPONS);
        simple("mosquito_bow", WEAPONS);
        simple("scorpion_bow", WEAPONS);
        simple("spider_bow", WEAPONS);
        simple("reaper_bow", WEAPONS);
        simple("cryptic_bow", WEAPONS);
        simple("sniper_bow", WEAPONS);
        simple("soulstealer_bow", WEAPONS);
        simple("spirit_bow", WEAPONS);
        simple("undead_bow", WEAPONS);
    }
}
